### ISSUE TITLE
No artifact path is set for function: "sumologicShipping"

### ISSUE THREAD

**Issue by onyxraven** [ACloudGuru/serverless-plugin-cloudwatch-sumologic#7]
I *Think* I have this setup right, but I'm running into the title'd error

```
  Your Environment Information -----------------------------
     OS:                 darwin
     Node Version:       4.3.2
     Serverless Version: 1.5.0
```

```
...
Serverless: Checking if serverless is managing logs via cloudformation
Serverless: Adding Cloudwatch to Sumologic lambda function

  Error --------------------------------------------------

     No artifact path is set for function: "sumologicShipping"
```

```
Error: No artifact path is set for function: "sumologicShipping"
    at AwsCompileFunctions.compileFunction (node_modules/serverless/lib/plugins/aws/deploy/compile/functions/index.js:71:13)
    at node_modules/serverless/lib/plugins/aws/deploy/compile/functions/index.js:212:39
    at Array.forEach (native)
```

I do have the serverless-build-plugin also installed, I think theres a conflict, where the new function isnt setup right for the build plugin.

**Comment by onyxraven** [comment]
Old ticket, can close
